[package]
name = "infiltrator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
copypasta = { version = "0.10.2", features = ["wayland"] }
directories = "6.0.0"
eframe = "0.36.2"
enigo = { version = "0.6.1", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
toml = "1.1.6"
wayland-client = "0.31.15"
